[package]
name = "rabbit_game"
version = "0.1.0"
authors = ["David Dovel <ddovel@uplandsoftware.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
